on:
  workflow_call:
    inputs:
      sqlcipher:
        type: string
        required: true
        description: "How to link sqlcipher, one of 'system' | 'static'"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: webapp

      - name: Cache .hak
        uses: actions/cache@v3
        with:
          key: ${{ hashFiles('./yarn.lock') }}
          path: |
            ./.hak

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install libsqlcipher-dev
        if: inputs.sqlcipher == 'system'
        run: sudo apt-get install -y libsqlcipher-dev

      - uses: actions/setup-node@v3
        with:
          cache: "yarn"

      # Does not need branch matching as only analyses this layer
      - name: Install Deps
        run: "yarn install --pure-lockfile"

      - name: Build Natives
        run: "yarn build:native"
        env:
          SQLCIPHER_STATIC: ${{ inputs.sqlcipher == 'static' && '1' || '' }}

      - name: Build App
        run: "yarn build --publish never -l"

      - name: Install .deb
        run: "sudo apt install ./dist/*.deb"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-sqlcipher-${{ inputs.sqlcipher }}
          path: dist
          retention-days: 1
